# Generated by Django 3.2.4 on 2024-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='img_url',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
