# Generated by Django 4.2 on 2024-05-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=15)),
                ('grado_ricura', models.IntegerField()),
            ],
        ),
    ]
