# Generated by Django 4.2 on 2024-06-14 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('PCT', 'Paciente'), ('ADM', 'Administrador')], default='PCT')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponible', models.DateField()),
                ('hora_disponible', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('especialidad', models.CharField(choices=[('CG', 'Cirugía General'), ('CCV', 'Cirugía Cardiovascular'), ('CPD', 'Cirugía Pediátrica'), ('CPR', 'Cirugía Plástica y Reparadora'), ('DMT', 'Dermatología'), ('GO', 'Ginecología y Obstetricia'), ('PSQ', 'Psiquiatría'), ('TMT', 'Traumatología'), ('ANS', 'Anestesiología')])),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('agenda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva_horas.agenda')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='centro_medico_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva_horas.centromedico'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='especialista_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva_horas.especialista'),
        ),
    ]
