# Generated by Django 4.2 on 2024-06-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_horas', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_name',
            new_name='nombre',
        ),
    ]
