# Generated by Django 4.2 on 2024-06-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_horas', '0003_rename_customer_email_contactform_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='ontact_form_uuid',
            new_name='contact_form_uuid',
        ),
    ]
